spring:
  profiles:
    active: local
      # 어떤 배치도 실행하지 않겠다는 뜻. 이 상태에서 Program arguments에 job.name을 인수로 전달하여 원하는 배치만 실행한다.
  batch:
    job:
      name: ${job.name:NONE}
---
spring:
  datasource:
    url: jdbc:h2:mem:batch;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: local
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: mysql

